---
- name: NGINX | Install nginx
  apt: pkg=nginx state=present

- name: NGINX | Copy site config
  template: src=devsite.j2 dest=/etc/nginx/sites-enabled/default

- name: NGINX | Run nginx
  service: name=nginx state=started enabled=true