---
- hosts: djangodevbox
  gather_facts: False
  vars:
    system:
      hostname: "djangodevbox"
    postgres:
      name: "database"
      user: "username"
      password: "toor"
    django:
      projectdir: "project"
      static: "static"
      media: "media"
    uwsgi:
      appname: "default"
      processes: 5

  roles:
    - system
    - python
    - nginx
    - uwsgi
    - djangobase
