---
- name: DjangoBase | Symlink project
  action: file src=/vagrant/{{ django.projectdir }} dest=/var/www/devsite state=link

- name: DjangoBase | Create VirtualEnv
  command: virtualenv /var/www/devsite-env --no-site-packages

